version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - yarn install --production=false

  build:
    commands:
      - yarn run lint
      - yarn next build
      - yarn next export

  post_build:
    commands:
      - aws s3 sync ./out s3://vectorly.app --delete
      - aws cloudfront create-invalidation --distribution-id E3CARKB1J1X10G --paths "/*"
